#!/bin/sh

if ! [ -f Dockerfile ]; then
  printf >&2 "You don't appear to be in the correct directory\n"
  exit 1
fi

case $1 in
  build)
    docker build -t cves-scorer .
  ;;
  run)
    docker run -it -v cves-scorer:/var/lib/cves/data cves-scorer
  ;;
  *)
    printf "Usage: ./cves-scorer-docker [build|run]\n"
  ;;
esac
