#!/bin/sh

build() {
  docker build -t cves-scorer .
}

run() {
  docker run -it -v cves-scorer:/var/lib/cves cves-scorer
}

if ! [ -f Dockerfile ]; then
  printf >&2 "You don't appear to be in the correct directory\n"
  exit 1
fi

case $1 in
  build)
    build
  ;;
  run)
    run
  ;;
  *)
    build
    run
  ;;
esac
