#!/bin/sh

cd /usr/lib/cves || exit 1

if ! [ -f /var/lib/cves/cves.db ]; then
  printf ':: Populating database ...\n'
  bzip2 -dc /usr/lib/cves/cves-dump.sql.bz2 | sqlite3 /var/lib/cves/cves.db
fi

./sentence-score
